name: Build Status 

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test_requirements.txt
        pip install -e . -v
    - name: Lint with ruff
      run: ruff check
    - name: Check formatting
      run: black --check EXOSIMS tests
    - name: Run tests and coverage
      run: coverage run -m unittest discover -v
    - name: Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          coveralls --service=github
